{% set name = "allthekernels" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f91aecdf00e8474920b47fa3658590c9c66bc7783bfed05af94f3cfbcdf6940 

build:
  noarch: python
  number: 0
  # Using the --no-binary option to prevent pip to build the wheel, so that
  # the full path to python is included in the kernelspec.
  script: "{{ PYTHON }} -m pip install . -vv --no-binary :all:"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - ipykernel >=4.3
    - jupyter_client >=5
    - pyzmq >=15.2
    - tornado >=4

test:
  imports:
    - allthekernels

about:
  home: http://github.com/minrk/allthekernels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Multiplexing kernel for Jupyter'
  description: |
    Multiplexing kernel for Jupyter
    Use all your kernels in a single notebook.
    Specify which kernel each should run by starting the cell with
    >kernel-name    
  doc_url: https://github.com/minrk/allthekernels
  dev_url: https://github.com/minrk/allthekernels

extra:
  recipe-maintainers:
    - SylvainCorlay
    - wolfv
    - minrk
    - JohanMabille
